name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CLI tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm -v
          sudo npm install -g markdownlint-cli
      - name: Lints Markdown files
        run: |
          find . -name "*.md" -exec markdownlint {} \;
          yamllint -c .yamllint.yaml docs/**/*.yaml
